#API Configurations
case-prc-api: 
  http-listener:
    host: "localhost"
    port: "8081"
    path: "/api/*"
api:
  #Replace with respective autodiscovery id
  autodiscoveryID: "REPLACE_BY_USER"
customer-prc-api:  
  http-frequency: "5000"
  content-type: "application/json"
  base-path: "/"
  port: "80"
  response-timeout: "60000"
  path: "/api"
  connection-idle-timeout: "3000"
  http-reconnection-attempts: "2"
  #Replace with respective application hostname
  host: "customer-prc-api-impl-mule-application.de-c1.eu1.cloudhub.io"
transazione-prc-api:  
  http-frequency: "5000"
  content-type: "application/json"
  base-path: "/"
  port: "80"
  response-timeout: "60000"
  path: "/api"
  connection-idle-timeout: "3000"
  http-reconnection-attempts: "2"
  #Replace with respective application hostname
  host: "transazione-prc-api-impl-mule-application.de-c1.eu1.cloudhub.io"  
application-msgs: 
  #JIRA Issue create success message
  jira-create-success-message:  "Issue Created Successfully"
  success-msg: "Success"
  # No Route Matching Message
  no-match-route-found: "No Matching Route Found"
  #Before Connector logger message
  before-connector-call-message: "Before Connector Call"
  #After Connector logger message
  after-connector-call-message:  "After Connector Call"
  #SNOW Incident create success message
  incident-create-success-message: "Incident Created Successfully"
#MUNIT Message for failed tests
munit: 
  message: "Test Failed"

#retry
retry:
   http: 
    delayMillisecs: "3000"
    numRetries: "3"
